# Generated by Django 6.0.5 on 2026-06-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
