# Generated by Django 6.0.5 on 2026-06-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('personas', models.CharField(choices=[('1', '1 persona'), ('2', '2 personas'), ('3', '3 personas'), ('4', '4 personas'), ('5', '5+ personas')], default='2', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nota', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('confirmada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
